on: 
  push:
    branches:
      - master

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test the workflow
      uses: ./
      with:
        version: 2.3.1
    - name: Check the existence of kubebuilder
      run: |-
        cd /usr/local/kubebuilder/bin
        if [[ -f "./kubectl" ]] && [[ -f "./kube-apiserver" ]] && [[ -f "./etcd" ]] && [[ -f "./kubebuilder" ]]; then
          echo "All binaries from kubebuilder have been installed!"
        else
          echo "Cannot find the binaries from kubuilder!"
        fi
