on: 
  push:
    branches:
      - master

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test the workflow
      uses: ./
      with:
        version: 2.3.1
    - name: Check the existence of kubebuilder
      run: |-
        if [[ ! -d /usr/local/kubebuilder ]]; then
          echo "No kubebuilder installed"
          exit 1
        fi
